# Generated by Django 5.0.6 on 2024-05-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_photogallery_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
